#!/bin/zsh

export PATH=/usr/local/bin:$PATH



echo "Start Precommit Checks..."

function lintit () {

x=0

ESOUTPUT=$(git diff --diff-filter=ACMR --cached --name-only | grep -E '(.js)$')
  a=("${(f)ESOUTPUT}")
  echo "Start ESLint Checks..."
  if [[ "$a" != "" ]]; then
    echo $a
    e=$(eslint -c hooks/eslintconfig.json --rulesdir hooks/custom-rules/ $a)
    echo $e
    if [[ "$e" != "" ]]; then
      echo "ERROR: Check eslint hints."
      x=1
    fi
  fi

echo "Done ESLint Checks..."

  SCSSOUTPUT=$(git diff --diff-filter=ACMR --cached --name-only | grep -E '(.scss)$')
  s=("${(f)SCSSOUTPUT}")
  echo "Start SCSS-Lint Checks..."
  if [[ "$s" != "" ]]; then
    sr=$(scss-lint -c hooks/scssconfig.yml $s)
    echo $sr
    if [[ "$sr" != "" ]]; then
      echo "ERROR: Check scss errors."
      x=1
    fi
  fi

  echo "Done SCSS-Lint Checks..."

  echo "Start Flow Checks..."
  fr=$(flow)
  if [[ "$fr" != "No errors!" ]]; then
    echo $fr
    echo "ERROR: Check for Flow Errors"
    x=1
  fi

  echo "Done Flow Checks..."

  if [[ "$x" != 0 ]]; then
    exit 1
  fi
}
lintit

  