#!/bin/zsh

export PATH=/usr/local/bin:$PATH

echo "Start Precommit Checks..."

function lintit () {

x=0

ESOUTPUT=$(git diff --diff-filter=ACMR --cached --name-only | grep -E '(.js)$')
  a=("${(f)ESOUTPUT}")
  echo "Start ESLint Checks..."
  if [[ "$a" != "" ]]; then
    echo $a
    e=$(eslint -c eslintconfig.json --rulesdir custom-rules/ $a)
    echo $e
    if [[ "$e" != "" ]]; then
      echo "ERROR: Check eslint hints."
      x=1
    fi
  fi

  SCSSOUTPUT=$(git diff --diff-filter=ACMR --cached --name-only | grep -E '(.scss)$')
  s=("${(f)SCSSOUTPUT}")
  echo "Start SCSS-Lint Checks..."
  if [[ "$s" != "" ]]; then
    sr=$(scss-lint -c scssconfig.yml $s)
    echo $sr
    if [[ "$sr" != "" ]]; then
      echo "ERROR: Check scss errors."
      x=1
    fi
  fi

  if [[ "$x" != 0 ]]; then
    exit 1
  fi
}
lintit

  